include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    - public_member_api_docs
    - close_sinks
