name: iabtcf_consent_info

packages:
  - .
  - packages/**

ide:
  intellij: false

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  format:
    run: flutter format .

  format:check:
    run: flutter format --set-exit-if-changed .

  analyze:
    run: flutter analyze

  test:
    exec: flutter test
    select-package:
      dir-exists:
        - 'test'
