name: iabtcf_consent_info

packages:
  - .
  - packages/**

ide:
  intellij: false

scripts:
  format:
    run: dart format .

  format:check:
    run: dart format --set-exit-if-changed . --output=show

  analyze:
    run: flutter analyze

  test:
    exec: flutter test
    packageFilters:
      dirExists:
        - 'test'
