name: iabtcf_consent_info

packages:
  - .
  - packages/**

ide:
  intellij: false

scripts:
  format:
    run: flutter format .

  format:check:
    run: flutter format --set-exit-if-changed .

  analyze:
    run: flutter analyze

  test:
    exec: flutter test
    packageFilters:
      dirExists:
        - 'test'
