name: iabtcf_consent_info

dev_dependencies:
  pedantic: 1.11.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

packages:
  - packages/**

scripts:
  check_formatting: melos exec -- flutter format --set-exit-if-changed .

  analyze:
    run: melos exec -c 1 -- flutter analyze

  test:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      dir-exists:
        - 'test'
  
  integration_test:web:
    run: melos exec -- 
      flutter drive 
        --no-pub 
        -d web-server 
        --driver test_driver/integration_test.dart 
        --target integration_test/e2e_test.dart
    select-package:
      scope:
        - iabtcf_consent_info_web_example
