name: CI

env:
  FLUTTER_VERSION: 3.3.9
  MELOS_VERSION: 2.8.0

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install Melos
        run: flutter pub global activate melos $MELOS_VERSION

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Check formatting
        run: melos format:check

      - name: Analyze Dart code
        run: melos analyze

      - name: Run tests
        run: melos test
