name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Bootstrap packages
        run: melos bootstrap

      - name: Check formatting
        run: melos format:check

      - name: Analyze Dart code
        run: melos analyze

      - name: Run tests
        run: melos test
